### ISSUE TITLE
Dockerfile to fix broken dev environment

### ISSUE THREAD

**Issue by Mknight492** [virtualstate/virtualstate.dev#1]
## 🚀 Feature Proposal

add a Dockerfile and published docker image for virtualstate.dev

## Motivation

Reliable access to the dev environment,

## Example

Currently when I clone the repo, install the packages and try to run the dev sever I get the following error:

(node:65312) UnhandledPromiseRejectionWarning: Error: Not supported                                 e, promise rejections that are not handled will terminate the Node.js pro
    at C:\dev2\virtualState\virtualstate.dev\node_modules\snowpack\lib\index.js:34012:15
    
    It might be an environment issue and this sort of thing stops people trying the library out which significantly impacts adoption.

**Comment by fabiancook** [comment]
I am using Node 15+ for this project, which is what is being used for its build on netlify, I will add this to the package and additionally add a dockerfile to ensure it can be ran anywhere

**Comment by fabiancook** [comment]
```
$ docker build . -t <your id>/virtualstate.dev
$ docker run -p 49160:8080 -d <your id>/virtualstate.dev 
```

![image](https://user-images.githubusercontent.com/4337080/123057630-25baa200-d45c-11eb-9738-b03362479d86.png)
